INSERT INTO AntiCharaTable (chara_name, anti_chara_name) VALUES ('d.va','sombra,reaper,zarya'),
  ('winston','reaper,roadhog,brigitte,d.va'),
  ('orisa','phara,reaper,hazno'),
  ('zarya','phara,mccree,sombra'),
  ('sigma','symmetra,phara,mei,doomfist,wrecking ball'),
  ('reinhart','phara,mei,reaper'),
  ('wrecking ball','sombra,reaper,roadhog,mercy,brigitte,ana'),
  ('roadhog','zarya,reaper,mercy,brigitte,ana'),
  ('ashe','winston,genji,tracer,widowmaker,mercy'),
  ('widowmaker','widowmaker,genji,hazno,winston,wrecking ball'),
  ('echo','ashe,soldier76,mccree,widowmaker,d.va'),
  ('genji','moira,symmetra,mei,winston,brigitte'),
  ('symmetra','phara,winston,wrecking ball,mercy'),
  ('junkrat','phara,mccree,roadhog'),
  ('soldier76','genji,mercy,doomfist'),
  ('sombra','sombra'),
  ('tracer','mccree,sombra,roadhog,brigitte,sombra'),
  ('torbjorn','ashe,hazno,mccree,widowmaker,phara'),
  ('doomfist','sombra,mccree,brigitte,reaper,ana'),
  ('hazno','winston,genji,tracer,doomfist,sigma'),
  ('bastion','phara,junkrat,sombra,genji,sigma,hazno,ana,roadhog,d.va'),
  ('phara','ashe,mccree,soldier76,d.va,baptiste,widowmaker'),
  ('mccree','mccree,sigma,roadhog'),
  ('mei','phara,mccree,reaper'),
  ('reaper','mccree,ana,phara,brigitte'),
  ('ana','winston,tracer,widowmaker'),
  ('zenyatta','winston,doomfist,genji,sombra,tracer,phara'),
  ('baptiste','doomfist,widowmaker,tracer,wrecking ball'),
  ('brigitte','mccree,phara,sigma,ashe,hazno'),
  ('mercy','winston,tracer,moira,mccree,doomfist,d.va,genji'),
  ('moira','mccree,d.va,ashe,widowmaker'),
  ('lucio','sombra,phara,brigitte,mccree,winston');